import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "PDF-Generator-App",
  description: "Generated by create next app",
};

import "./globals.css";
import { FormProvider } from "@/components/FormContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <FormProvider>{children}</FormProvider>
      </body>
    </html>
  );
}
